### ISSUE TITLE
[Meta] HTTP/1.x support

### ISSUE THREAD

**Issue by thislight** [thislight/haiya#1]
- [x] Receive request and send response
 - [x] `Transfer-Encoding: chunked`
 - [x] Receive request body
 - [x] Send compressed data (only gzip)
